server.port: 8080
spring:
  application:
    name: Traffic Signs Server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db?serverTimezone=UTC;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
info.version: @version@