name: Java Sping CI with Gradle

on:
  push:
    branches: [ master, develop, feat/ci/cd ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unit and Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Test with Gradle
        run: ./mvnw clean package
